"""
3D animated visualizer for the GPU satellite simulation output.

Usage:
    python visualize_3d.py

This script expects trajectory_samples.csv generated by satellite_sim.
"""

import math
import os
from typing import Dict, Optional, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

R_EARTH = 6.371e6  # m

CLASS_COLORS = {
    1: "#2ecc71",  # stable
    2: "#e74c3c",  # escape
    3: "#3498db",  # crash
}

CLASS_LABELS = {
    1: "Stable",
    2: "Escape",
    3: "Crash",
}

# Global reference for notebook environments so animation is not garbage-collected.
ANIMATION_REF = None


def is_notebook() -> bool:
    try:
        from IPython import get_ipython
        shell = get_ipython()
        if shell is None:
            return False
        return shell.__class__.__name__ in ("ZMQInteractiveShell", "Shell")
    except Exception:
        return False


def rotation_matrix_x(angle_rad: float) -> np.ndarray:
    c = math.cos(angle_rad)
    s = math.sin(angle_rad)
    return np.array(
        [
            [1.0, 0.0, 0.0],
            [0.0, c, -s],
            [0.0, s, c],
        ]
    )


def rotation_matrix_z(angle_rad: float) -> np.ndarray:
    c = math.cos(angle_rad)
    s = math.sin(angle_rad)
    return np.array(
        [
            [c, -s, 0.0],
            [s, c, 0.0],
            [0.0, 0.0, 1.0],
        ]
    )


def to_3d_track(x_m: np.ndarray, y_m: np.ndarray, sat_id: int) -> np.ndarray:
    z = np.zeros_like(x_m)
    track = np.vstack([x_m, y_m, z])

    # Deterministic orientation spread so trajectories are visible in 3D.
    inclination_deg = 15.0 + (sat_id % 7) * 8.0
    raan_deg = (sat_id * 37) % 360

    rx = rotation_matrix_x(math.radians(inclination_deg))
    rz = rotation_matrix_z(math.radians(raan_deg))
    rot = rz @ rx
    return rot @ track


def load_trajectories(path: str) -> Tuple[Dict[int, pd.DataFrame], Dict[int, np.ndarray], int]:
    df = pd.read_csv(path)
    if df.empty:
        raise RuntimeError("trajectory_samples.csv is empty")

    grouped = {}
    transformed = {}
    max_step = 0

    for sat_id, sub in df.groupby("sat_id"):
        sub = sub.sort_values("step").reset_index(drop=True)
        grouped[sat_id] = sub

        xyz = to_3d_track(sub["x_m"].to_numpy(), sub["y_m"].to_numpy(), int(sat_id))
        transformed[sat_id] = xyz

        max_step = max(max_step, int(sub["step"].max()))

    return grouped, transformed, max_step


def main() -> Optional[FuncAnimation]:
    global ANIMATION_REF

    csv_path = "trajectory_samples.csv"
    if not os.path.exists(csv_path):
        print("trajectory_samples.csv not found. Run satellite_sim first.")
        return None

    tracks, transformed, max_step = load_trajectories(csv_path)
    sat_ids = sorted(tracks.keys())

    fig = plt.figure(figsize=(12, 9))
    ax = fig.add_subplot(111, projection="3d")

    # Draw Earth sphere.
    u = np.linspace(0, 2 * np.pi, 72)
    v = np.linspace(0, np.pi, 36)
    x = (R_EARTH * np.outer(np.cos(u), np.sin(v))) / 1000.0
    y = (R_EARTH * np.outer(np.sin(u), np.sin(v))) / 1000.0
    z = (R_EARTH * np.outer(np.ones_like(u), np.cos(v))) / 1000.0
    ax.plot_surface(x, y, z, rstride=1, cstride=1, color="#95c8d8", alpha=0.45, linewidth=0)

    # Rotating meridian line to show Earth rotation.
    meridian_radius = R_EARTH / 1000.0
    meridian_theta = np.linspace(-np.pi / 2, np.pi / 2, 200)
    meridian_base = np.vstack([
        np.zeros_like(meridian_theta),
        meridian_radius * np.cos(meridian_theta),
        meridian_radius * np.sin(meridian_theta),
    ])
    (meridian_line,) = ax.plot([], [], [], color="black", linewidth=1.5, alpha=0.8)

    # Launch site marker at equator (rotates with Earth).
    launch_site_base = np.array([[meridian_radius], [0.0], [0.0]])
    launch_site = ax.scatter([], [], [], s=55, color="#f39c12", label="Launch site")

    # Satellite artists.
    sat_lines = {}
    sat_points = {}
    sat_classes = {}
    sat_last_steps = {}

    for sat_id in sat_ids:
        sat_class = int(tracks[sat_id]["class"].iloc[0])
        sat_classes[sat_id] = sat_class
        sat_last_steps[sat_id] = int(tracks[sat_id]["step"].iloc[-1])

        color = CLASS_COLORS.get(sat_class, "gray")
        (line,) = ax.plot([], [], [], color=color, linewidth=1.4, alpha=0.9)
        (point,) = ax.plot([], [], [], marker="o", color=color, markersize=5)
        sat_lines[sat_id] = line
        sat_points[sat_id] = point

    max_radius_km = 0.0
    for sat_id in sat_ids:
        xyz = transformed[sat_id] / 1000.0
        max_radius_km = max(max_radius_km, float(np.max(np.sqrt(np.sum(xyz * xyz, axis=0)))))

    lim = max(max_radius_km * 1.05, meridian_radius * 1.8)
    ax.set_xlim(-lim, lim)
    ax.set_ylim(-lim, lim)
    ax.set_zlim(-lim, lim)
    ax.set_box_aspect([1, 1, 1])
    ax.set_xlabel("X (km)")
    ax.set_ylabel("Y (km)")
    ax.set_zlabel("Z (km)")
    ax.set_title("3D Orbit Animation: Rotating Earth and Satellite Outcomes")

    legend_handles = []
    for cls in [1, 2, 3]:
        handle = plt.Line2D([0], [0], color=CLASS_COLORS[cls], lw=2, label=CLASS_LABELS[cls])
        legend_handles.append(handle)
    legend_handles.append(plt.Line2D([0], [0], marker="o", color="#f39c12", lw=0, label="Launch site"))
    ax.legend(handles=legend_handles, loc="upper left")

    info_text = ax.text2D(0.01, 0.97, "", transform=ax.transAxes)

    # Speed up long tracks for smoother preview.
    stride = 10 if max_step > 1600 else 5 if max_step > 800 else 2
    frame_steps = list(range(0, max_step + 1, stride))
    if frame_steps[-1] != max_step:
        frame_steps.append(max_step)

    def update(frame_idx: int):
        step_now = frame_steps[frame_idx]

        # Earth rotation indicator (visual, not physically scaled to simulation time).
        earth_angle = 2.0 * np.pi * frame_idx / max(1, len(frame_steps) - 1)
        rz = rotation_matrix_z(earth_angle)

        mer = rz @ meridian_base
        meridian_line.set_data(mer[0], mer[1])
        meridian_line.set_3d_properties(mer[2])

        site = rz @ launch_site_base
        launch_site._offsets3d = ([site[0, 0]], [site[1, 0]], [site[2, 0]])

        visible_stable = 0
        visible_escape = 0
        visible_crash = 0

        for sat_id in sat_ids:
            sat_class = sat_classes[sat_id]
            last_step = sat_last_steps[sat_id]

            # Escape/crash satellites disappear after they fall out or re-enter.
            if sat_class in (2, 3) and step_now > last_step:
                sat_lines[sat_id].set_data([], [])
                sat_lines[sat_id].set_3d_properties([])
                sat_points[sat_id].set_data([], [])
                sat_points[sat_id].set_3d_properties([])
                continue

            steps = tracks[sat_id]["step"].to_numpy()
            upto = np.searchsorted(steps, step_now, side="right")
            if upto <= 0:
                sat_lines[sat_id].set_data([], [])
                sat_lines[sat_id].set_3d_properties([])
                sat_points[sat_id].set_data([], [])
                sat_points[sat_id].set_3d_properties([])
                continue

            xyz = transformed[sat_id][:, :upto] / 1000.0
            sat_lines[sat_id].set_data(xyz[0], xyz[1])
            sat_lines[sat_id].set_3d_properties(xyz[2])

            sat_points[sat_id].set_data([xyz[0, -1]], [xyz[1, -1]])
            sat_points[sat_id].set_3d_properties([xyz[2, -1]])

            if sat_class == 1:
                visible_stable += 1
            elif sat_class == 2:
                visible_escape += 1
            elif sat_class == 3:
                visible_crash += 1

        info_text.set_text(
            f"Step: {step_now}    Visible -> Stable: {visible_stable}, Escape: {visible_escape}, Crash: {visible_crash}"
        )

        artists = [meridian_line, launch_site, info_text]
        artists.extend(sat_lines.values())
        artists.extend(sat_points.values())
        return artists

    anim = FuncAnimation(fig, update, frames=len(frame_steps), interval=40, blit=False, repeat=True)
    ANIMATION_REF = anim

    plt.tight_layout()

    # In notebooks/Colab, explicitly render inline to avoid "Animation was deleted" warnings.
    if is_notebook():
        try:
            from IPython.display import HTML, display
            display(HTML(anim.to_jshtml()))
            plt.close(fig)
            return anim
        except Exception:
            # Fallback to regular show if HTML rendering fails.
            pass

    plt.show()
    return anim


if __name__ == "__main__":
    main()
